---
title: "R Notebook"
output: html_notebook
author: "David"
---

# 1a Simulation of system

\begin{aligned}
Y_{n+1}^{1} &=Y_{n}^{1}+\theta_{3}\left(Y_{n}^{1}+Y_{n}^{2}-\frac{1}{3}\left(Y_{n}^{1}\right)^{3}+\theta_{4}\right) \Delta+\sigma \Delta W_{n+1}^{1} \\
Y_{n+1}^{2} &=Y_{n}^{2}-\frac{1}{\theta_{3}}\left(Y_{n}^{1}+\theta_{2} Y_{n}^{2}-\theta_{1}\right) \Delta
\end{aligned}

### Without stochasticity

```{r}
# Let's define a function to simulate the system
SDEsim = function(y1_init = -1.9, y2_init=1.2, delta = 2^(-9), theta1=0.7, theta2=0.8, theta3=3.0, theta4=-0.34, sigma=0, T=100/delta){
    # Init
  D = list()
  y1 = rep(NaN, T); y1[1] = y1_init;
  y2 = rep(NaN, T); y2[1] = y2_init;
  
    # Run the system
  for (i in 1:(T-1)){
    y1[i+1] = y1[i] + theta3*(y1[i] + y2[i] - 1/3*y1[i]^3 + theta4)*delta + sigma*rnorm(1,mean=0,sd=sqrt(delta))
    y2[i+1] = y2[i] - 1/theta3 * (y1[i] + theta2*y2[i] - theta1) * delta
  }
    # Save and return list
  D$y1 = y1
  D$y2 = y2
  return(D)
}
sim = SDEsim(sigma=0)
plot(sim$y1, sim$y2, cex=0.01)
```

### Introducing stochasticity
for sigma=0.1, 0.2, 0.3, 0.4
```{r}
par(mfrow=c(2,2))
for (sd in c(0.1, 0.2, 0.3, 0.4)){
  sim = SDEsim(sigma=sd)
  plot(sim$y1, sim$y2, cex=0.1, main=sprintf("sigma = %.2f", sd))
}
```

## 1b (MANGLER)


# Bygning
# 2a

```{r}
setwd("~/Documents/DTU/3. Semester (MSc)/Advanced Time Series/Assignments/3-Assignment/CompEx3_E18")
ExampleRoom1.R
```


















